### ISSUE TITLE
Challenge: subarray_sum

### ISSUE THREAD

**Issue by Lotfullah21** [MIT-Emerging-Talent/2024-group-08-collaboration-practice#6]

**Comment by KHH-AKA-Lucifer** [comment]
Hi Brother Lotfullah,
I ran test_file  on the solution that you have provided and found out some test fails. I hope you will fix them soon.
Regards,
Kaung Hein Htet

**Comment by Lotfullah21** [comment]
I fixed it, you can check it now.

**Comment by KHH-AKA-Lucifer** [comment]
It's a wonderful solution. Well done, brother. Have a good day.
